foo's not unix

diff --git a/caddy/PKGBUILD b/caddy/PKGBUILD
--- a/caddy/PKGBUILD
+++ b/caddy/PKGBUILD
@@ -14,8 +14,8 @@ sha256sums=('558e9f4e063228db0e46f962cd270e9b38af3d61ee9eecf6ef1e177552f3c8c7'
 
 package() {
 	install -Dm755 "${srcdir}/caddy-cloudflare-linux-amd64-${pkgver}" "${pkgdir}/usr/bin/caddy"
-	if ! id -u foo &>/dev/null || [ "$(id -u foo)" -ne 1000 ]; then
-		echo "Error: User 'foo' with UID 1000 does not exist."
+	if ! id -u unix &>/dev/null || [ "$(id -u unix)" -ne 1000 ]; then
+		echo "Error: User 'unix' with UID 1000 does not exist."
 		return 1  # Exit with a non-zero status to indicate failure
 	fi
 	install -Dm644 "${srcdir}/caddy.service" "${pkgdir}/etc/systemd/system/caddy.service"
